
inherit: base.yaml

method:
  name: proser
  num_dummy: 5             
  beta: 1.0               
  gamma: 0.1              
  mixup_alpha: 2.0        
  finetune:
    lr: 0.001             
    epochs: 50
    momentum: 0.9
    weight_decay: 0.0005
    scheduler: cosine
    batch_size: 128

init_from: vanilla
