
inherit: base.yaml

method:
  name: cdan
  
  disc_hidden: 256
  disc_dropout: 0.5
  domain_loss_weight: 1.0
  grl_gamma: 10.0
  grl_max_alpha: 1.0
  
  use_entropy_conditioning: false
  detach_features: false
  detach_probs: false
  
  normalize_multilinear: true

controlled_study:
  enabled: false
